#!/bin/sh позволяет перед отправкой коммита проверить все скрипты
. "$(dirname "$0")/_/husky.sh"

#npm run build:prod
# npm run lint:ts
npx lint-staged # faster (check only changed files)
#npm run lint:scss
#npm run test:unit
#npm run storybook:build
#npm run test:ui
